obm = 'fabrication_utilities.ObservationMeasurements'
sm = 'StartingMaterial'

dir_path = {
    'dir1': 'fabrication_facilities.schema_packages.add.ICP_CVD',
    'dir2': 'fabrication_facilities.schema_packages.add.Spin_Coating',
    'dir3': 'fabrication_facilities.schema_packages.transform.EBL',
    'dir4': 'fabrication_facilities.schema_packages.transform.FIB',
    'dir5': 'fabrication_facilities.schema_packages.remove.ICP_RIE',
    'dir6': 'fabrication_facilities.schema_packages.remove.WetCleaning',
    'dir7': 'fabrication_facilities.schema_packages.transform.ResistDevelopment',
    'dir8': 'fabrication_facilities.schema_packages.add.Bonding',
    'dir9': 'fabrication_facilities.schema_packages.transform.Annealing',
    'dir10': 'fabrication_facilities.schema_packages.transform.LTODensification',
    'dir11': 'fabrication_facilities.schema_packages.transform.ThermalOxidation',
    'dir12': 'fabrication_facilities.schema_packages.transform.Dicing',
    'dir13': 'fabrication_facilities.schema_packages.transform.Doping',
    'dir14': 'fabrication_facilities.schema_packages.transform.LabelingCleaning',
    'dir15': 'fabrication_facilities.schema_packages.transform.SOD',
    'dir16': 'fabrication_facilities.schema_packages.transform.Track',
    'dir17': 'fabrication_facilities.schema_packages.add.ElectronGun',
    'dir18': 'fabrication_facilities.schema_packages.add.Sputtering',
    'dir19': 'fabrication_facilities.schema_packages.add.SOG',
    'dir20': 'fabrication_facilities.schema_packages.remove.RIE',
    'dir21': 'fabrication_facilities.schema_packages.remove.WetEtching',
    'dir22': 'fabrication_facilities.schema_packages.remove.Stripping',
    'dir23': f'fabrication_facilities.schema_packages.{obm}',
    'dir24': f'fabrication_facilities.schema_packages.fabrication_utilities.{sm}',
    'dir25': 'fabrication_facilities.schema_packages.transform.Baking',
    'dir26': 'fabrication_facilities.schema_packages.remove.DRIE_BOSCH',
    'dir27': 'fabrication_facilities.schema_packages.add.PECVD',
    'dir28': 'fabrication_facilities.schema_packages.add.LPCVD',
}
